language: rust

rust:
  - stable
arch:
    - amd64
    - arm64
cache: cargo

before_script:
  - rustup component add rustfmt-preview
  - rustup component add clippy

script:
  - cargo fmt --all -- --check
  - cargo check --all
  - cargo clippy --all
  - cargo build --all
  - cargo test --all
